#Предложения
## Создание нового предложения
POST http://localhost:4000/rent-offers HTTP/1.1
X-token: 'somesupertoken'
Content-Type: application/json

{
  "title": "validation test",
  "description": "long description for validation testoffer",
  "city": "Amsterdam",
  "previewImage": "preview.jpg",
  "images": [
        "offer-image-7.jpg",
        "offer-image-6.jpg",
        "offer-image-1.jpg",
        "offer-image-2.jpg",
        "offer-image-4.jpg",
        "offer-image-8.jpg"
  ],
  "isPremium": true,
  "type": "hotel",
  "bedrooms": 5,
  "maxAdults": 3,
  "price": 48410,
  "goods": [
        "Washer",
        "Laptop"
  ],
  "advertiserId": "64760b2a6a803a09ab8e9a2f",
  "latitude": 50.837557,
  "longitude": 4.351697
}
###

## Получить список предложений
GET http://localhost:4000/rent-offers HTTP/1.1
###

## Получить список премиальных предложений города
GET http://localhost:4000/rent-offers/premium?city=Paris HTTP/1.1
###

## Получить всю информацию о предложении
GET http://localhost:4000/rent-offers/6487275952b1fd03b2bbcca6 HTTP/1.1
###

## Обновить информацию о предложении
PATCH http://localhost:4000/rent-offers/6487275652b1fd03b2bbcca3 HTTP/1.1
X-token: 'somesupertoken'
Content-Type: application/json
{
  "isPremium" : false,
  "bedrooms" : 2,
  "goods" : [
    "Laptop"
  ]
}
###

## Удалить предложение
DELETE http://localhost:4000/rent-offers/64760b2a6a803a09ab8e9a31 HTTP/1.1
X-token: 'somesupertoken'
###

##Получить список комментариев к офферу
GET http://localhost:4000/rent-offers/6487275352b1fd03b2bbcca0/comments HTTP/1.1
###
