#Предложения
## Создание нового предложения
POST http://localhost:4000/rent-offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbmV3dGVzdC5jb20iLCJpZCI6IjY1NDUwODJjMjU4OWFmYzAyZTY4YjY0ZiIsImlhdCI6MTY5OTAyMjg5MiwiZXhwIjoxNjk5MTA5MjkyfQ.hqjqi6iRi2aiOv_ZGeD2kg2LfLOUkVBQXYCGyG89xjk
Content-Type: application/json

{
  "title": "validation test for delete",
  "description": "long description for validation testoffer",
  "city": "Amsterdam",
  "previewImage": "preview.jpg",
  "images": [
        "offer-image-7.jpg",
        "offer-image-6.jpg",
        "offer-image-1.jpg",
        "offer-image-2.jpg",
        "offer-image-4.jpg",
        "offer-image-8.jpg"
  ],
  "isPremium": true,
  "type": "hotel",
  "bedrooms": 5,
  "maxAdults": 3,
  "price": 48410,
  "goods": [
        "Washer",
        "Laptop"
  ],
  "latitude": 50.837557,
  "longitude": 4.351697
}

###

## Получить список предложений
GET http://localhost:4000/rent-offers?count=4 HTTP/1.1

###

## Получить список премиальных предложений города
GET http://localhost:4000/rent-offers/premium?city=Paris HTTP/1.1
###

## Получить всю информацию о предложении
GET http://localhost:4000/rent-offers/65325655cef4c3c2a2d512a0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImctZWFzeUBiZWVub24uY29tIiwiaWQiOiI2NDc2MGIyYTZhODAzYTA5YWI4ZTlhMmYiLCJpYXQiOjE2ODcyNjE5NTcsImV4cCI6MTY4NzM0ODM1N30.1HClWaMKeh2u07Ts62-DjvsGwtYdFRG83moghpBfOjg


###

## Обновить информацию о предложении
PATCH http://localhost:4000/rent-offers/65325655cef4c3c2a2d512a0 HTTP/1.1
X-token: 'somesupertoken'
Content-Type: application/json
{
  "isPremium" : false,
  "bedrooms" : 2,
  "goods" : [
    "Laptop"
  ]
}
###

## Удалить предложение
DELETE http://localhost:4000/rent-offers/65325655cef4c3c2a2d512a0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImctZWFzeUBiZWVub24uY29tIiwiaWQiOiI2NDc2MGIyYTZhODAzYTA5YWI4ZTlhMmYiLCJpYXQiOjE2ODcyNjE5NTcsImV4cCI6MTY4NzM0ODM1N30.1HClWaMKeh2u07Ts62-DjvsGwtYdFRG83moghpBfOjg


###

##Получить список комментариев к офферу
GET http://localhost:4000/rent-offers/65325655cef4c3c2a2d512a0/comments HTTP/1.1
###

## Загрузка preview
POST  http://localhost:2000/rent-offers/64974b9cbc8fdadc5a227253/preview HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbmV3dGVzdC5jb20iLCJpZCI6IjY0OTIxZTgxNGQwNTAzMWI5NGIzOGQ5ZCIsImlhdCI6MTY4NzYzNjg0MywiZXhwIjoxNjg3NzIzMjQzfQ.58iVuwbVZAXdwfo6m_aW1WV5jivW8R6tvNBPVjcWL2A
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="preview-image"; filename="preview.png"
Content-Type: image/png

< Q:/preview.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
