# Пользователи
## Регистрация нового пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "Keeekw",
  "email": "newUser@beenon.com",
  "password": "weakpass",
  "status": "pro",
  "avatarPath": "user-avatar-6.jpg"
}
###

## Авторизовать пользователя
POST http://localhost:4000/users/auth HTTP/1.1
Content-Type: application/json

{
  "email": "g-easy@beenon.com",
  "password": "weakpass"
}
###

## Запрос статуса авторизации пользователя
GET  http://localhost:4000/users/auth HTTP/1.1
X-token: 'somesupertoken'
###

## Завершения сеанса пользователя
DELETE http://localhost:4000/users/logout HTTP/1.1
X-token: 'somesupertoken'

###

## Добавление предложения в избранное
PUT http://localhost:4000/users/64760b2a6a803a09ab8e9a34/favorites/6487271d52b1fd03b2bbcc9d?isFav=1 HTTP/1.1

###

## Получить избранные предложения пользователя
GET http://localhost:4000/users/64760b2a6a803a09ab8e9a34/favorites/ HTTP/1.1

###
