# Пользователи
## Регистрация нового пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "testuser-3",
  "email": "user-no-advertiser@newtest.ru",
  "password": "weakpass1234",
  "status": "pro"
}
###

## Авторизовать пользователя
POST http://localhost:4000/users/auth HTTP/1.1
Content-Type: application/json

{
  "email": "user-no-advertiser@newtest.ru",
  "password": "weakpass1234"
}

###

## Запрос статуса авторизации пользователя
GET  http://localhost:4000/users/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjU0ZGRjZGQ0MGY2M2ZjOTBkNDJkYjJjIiwiaWF0IjoxNjk5NjAxNjI5LCJleHAiOjE2OTk2ODgwMjl9.2_HnUUp5QFu6wk620zYHiPsN93dviqd5v_ESPWDCLS8
###

## Завершения сеанса пользователя
DELETE http://localhost:4000/users/logout HTTP/1.1
X-token: 'somesupertoken'
###

## Добавление предложения в избранное
PUT http://localhost:4000/users/654e4e7640f63fc90d42db51/favorites/654de0fd40f63fc90d42db38?isFav=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LnJ1IiwiaWQiOiI2NTRlNGU3NjQwZjYzZmM5MGQ0MmRiNTEiLCJpYXQiOjE2OTk2MzA3ODYsImV4cCI6MTY5OTcxNzE4Nn0.vPRhAXEqXEjguRY0S3v3yfgDSCYzcyyPnBsed7eQybI


###

## Загрузка аватара пользователем

POST  http://localhost:4000/users/654ddcdd40f63fc90d42db2c/upload/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXItbm8tYWR2ZXJ0aXNlckBuZXd0ZXN0LmNvbSIsImlkIjoiNjU0ZGRjZGQ0MGY2M2ZjOTBkNDJkYjJjIiwiaWF0IjoxNjk5NjAxNjI5LCJleHAiOjE2OTk2ODgwMjl9.2_HnUUp5QFu6wk620zYHiPsN93dviqd5v_ESPWDCLS8
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/jpeg/image/png

< Q:/avatar.png
--boundary--

###
